name: Pull requests workflow
on:
  pull_request:
    branches: [ master ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build & Install
        run: mvn -B install -D skipTests --no-transfer-progress
      - name: Install Playwright
        run: mvn exec:java -e -D exec.mainClass=com.microsoft.playwright.CLI -D exec.args="install --with-deps"
      - name: Run tests
        run: xvfb-run mvn test -Dsurefire.suiteXmlFiles="testNG/smoke.xml"

      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: allure-results
          path: allure-results/

      - name: Send email after test run
        uses: cinotify/github-action@v1.1.2
        if: always()
        with:
          to: 'khiem_cao@epam.com','dung_pham@epam.com','luan_nguyen@epam.com'
          subject: 'Playwright test results for ${{ github.repository }}'
          body: 'The ${{ github.job }} job in ${{ github.workflow }} of ${{ github.repository }} has status ${{ job.status }}'